### ISSUE TITLE
postinstall: `typings install` failing

### ISSUE THREAD

**Issue by gauravmahajan31** [dudeofawesome/emoji-picker#1]
I am on MAC OS X Yosemite(10.10.1).
Cant seem to install emoji-picker because emoji-picker@0.0.6 postinstall: `typings install` is failing.

Attached is the npm-debug.log
[npm-debug.txt](https://github.com/dudeofawesome/emoji-picker/files/547111/npm-debug.txt)

**Comment by dudeofawesome** [comment]
When I made the module, I was working with Typescript, which used to rely on a CLI utility called typings to get metadata for packages. The NPM postinstall script called that command, which is why you're seeing that error. If you want to use the module right now, you could add `typings` as a dependency in your package.json.

I'll fix this soon though.

**Comment by gauravmahajan31** [comment]
Thanks for the quick response. Installing the typings package fixed it.

**Comment by dudeofawesome** [comment]
I actually just updated the package to `0.0.7` on NPM, which should fix the issue altogether, if you want to give that a shot.
